"""
Bolide Tanzania Warehouse & Production Management System - DEMO BACKEND
=====================================================================
A self-contained, dependency-light Flask server that serves DEMO data to
public/index.html (a rebranded copy of the DSA Warehouse frontend,
repointed at this server). Same underlying MOs/materials/workflows as the
original wms-dsa demo build - only the branding (logo, colors, name) and
this file changed.

This is NOT a real backend for any production system and never touches a
real database. Everything here lives in demo_data.json, generated by
generate_demo_data.py, and is mutated in-memory + persisted to disk so
picking materials, submitting reissue requests, approving them, adding
comments, etc. all "stick" between page reloads - exactly like the real
system, just backed by fixtures instead of SQL Server.

Run locally:
    pip install -r requirements.txt
    python demo_server.py
Then open http://127.0.0.1:5057/ in a browser - this server serves BOTH the
API and the frontend (public/index.html) on the same origin, so there's
nothing else to start.

Deploy (e.g. Render "Web Service"):
    Build command:  pip install -r requirements.txt
    Start command:  gunicorn demo_server:app
    (see render.yaml for a ready-made blueprint)

Logins:
    LANGA / DSA100%   -> Warehouse Admin   (role: admin)
    SIZWE / DSA200%   -> DSA Production    (role: dsaprod)
    SAM   / DSA300%   -> Management        (role: management)
    DANI  / DSA400%   -> Warehouse User    (role: warehouse)
"""
import json
import os
import threading
from datetime import datetime, timedelta

from flask import Flask, request, jsonify, send_from_directory

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SEED_PATH = os.path.join(BASE_DIR, "demo_data_seed.json")
STATE_PATH = os.path.join(BASE_DIR, "demo_data.json")
PUBLIC_DIR = os.path.join(BASE_DIR, "public")
PORT = int(os.environ.get("PORT", 5057))

app = Flask(__name__, static_folder=PUBLIC_DIR, static_url_path="")
LOCK = threading.Lock()

# ---------------------------------------------------------------------------
# Load / persist state
# ---------------------------------------------------------------------------

def load_db():
    path = STATE_PATH if os.path.exists(STATE_PATH) else SEED_PATH
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


DB = load_db()


def build_workstation_history():
    """Derive MOTrack.dbo.mo_workstation_history-shaped rows (who is/was at which
    workstation right now) from the workstation_completions production-tally
    table. These are two different real tables upstream; the completions table
    only carries qty in/out, while history carries the human-readable
    workstation name + employee_username the Assigned MOs screen renders."""
    rows = []
    for i, c in enumerate(DB["workstation_completions"]):
        rows.append({
            "id": i + 1,
            "mo_number": c["mo_number"],
            "workstation": c["workstation_name"],
            "workstation_id": c["workstation_id"],
            "employee_username": c["created_by"],
            "previous_workstation": None,
            "previous_workstation_id": None,
            "changed_at": c["started_at"],
            "notes": None,
            "change_type": "assigned",
        })
    return rows


WORKSTATION_HISTORY = build_workstation_history()


def save_db():
    with open(STATE_PATH, "w", encoding="utf-8") as f:
        json.dump(DB, f, indent=2)


def next_id(key):
    DB["next_ids"][key] = DB["next_ids"].get(key, 1) + 1
    return DB["next_ids"][key] - 1


def now_iso():
    return datetime.utcnow().isoformat()


# ---------------------------------------------------------------------------
# CORS - allow the demo HTML (opened via file:// or a local http server) to
# talk to this API from any origin.
# ---------------------------------------------------------------------------

@app.after_request
def add_cors_headers(resp):
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Access-Control-Allow-Headers"] = "Content-Type, Authorization"
    resp.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, DELETE, OPTIONS"
    return resp


@app.route("/<path:_any>", methods=["OPTIONS"])
def cors_preflight(_any):
    return ("", 204)


# ---------------------------------------------------------------------------
# Lookup helpers
# ---------------------------------------------------------------------------

def find_mo(mo_number):
    mo_number = (mo_number or "").strip().upper()
    for m in DB["mos"]:
        if m["mo_number"].upper() == mo_number:
            return m
    return None


def find_mo_by_moh(moh_id):
    try:
        moh_id = int(moh_id)
    except (TypeError, ValueError):
        return None
    for m in DB["mos"]:
        if m["moh_id"] == moh_id:
            return m
    return None


def find_user(identifier):
    identifier = (identifier or "").strip().lower()
    for u in DB["users"]:
        if u["name"].lower() == identifier or u["email"].lower() == identifier:
            return u
    return None


def user_public(u):
    return {k: v for k, v in u.items() if k != "password"}


def recompute_whmoitem(item_number):
    """Recalculate required_qty/shortage for a bulk stock item from live MO material lines."""
    outstanding = 0.0
    for line in DB["mo_material"]:
        if line["item_number"] == item_number:
            mo = find_mo_by_moh(line["moh_id"])
            if mo and mo.get("Status") in ("Transferred", "Completed", "Closed"):
                continue
            outstanding += max(0.0, line["Qty_Required"] - line["Qty_Issued"])
    for w in DB["whmoitems"]:
        if w["item_number"] == item_number:
            w["required_qty"] = round(outstanding, 1)
            w["required_qty_db"] = w["required_qty"]
            w["shortage"] = max(0.0, round(outstanding - w["total_stock"], 1))
            w["short"] = w["shortage"]
            w["updated_at"] = now_iso()


# ===========================================================================
# USERS / AUTH
# ===========================================================================

@app.route("/users/login", methods=["POST"])
def login():
    data = request.get_json(force=True, silent=True) or {}
    identifier = data.get("identifier", "")
    password = data.get("password", "")
    u = find_user(identifier)
    if not u or u["password"] != password:
        return jsonify({"error": "Invalid username/email or password"}), 401
    full_name = f"{u['name']} {u['surname']}"
    return jsonify({
        "success": True,
        "user": {
            "id": u["id"], "name": u["name"], "surname": u["surname"], "email": u["email"],
            "role": u["role"], "position": u["position"], "fullName": full_name,
            "is_admin": u["role"] == "admin",
        },
    }), 200


@app.route("/users/logout", methods=["POST"])
@app.route("/users/<int:user_id>/logout", methods=["POST"])
def logout(user_id=None):
    return jsonify({"status": "ok"}), 200


@app.route("/users/session", methods=["GET"])
def session_check():
    return jsonify({"active": True}), 200


@app.route("/users/<int:user_id>/heartbeat", methods=["POST"])
def heartbeat(user_id):
    return jsonify({"status": "ok"}), 200


@app.route("/users/activity", methods=["POST"])
def user_activity():
    return jsonify({"status": "ok"}), 200


@app.route("/users/<int:user_id>/activity", methods=["GET"])
def user_activity_get(user_id):
    return jsonify([]), 200


@app.route("/users", methods=["GET"])
def list_users():
    return jsonify([user_public(u) for u in DB["users"]]), 200


@app.route("/users/force-logout", methods=["POST"])
def force_logout():
    return jsonify({"status": "ok"}), 200


# ===========================================================================
# MANUFACTURING ORDERS
# ===========================================================================

@app.route("/mos", methods=["GET"])
def get_mos():
    return jsonify([m for m in DB["mos"] if m.get("Status") != "Closed"]), 200


@app.route("/mos/new", methods=["GET"])
def get_new_mos():
    return jsonify([m for m in DB["mos"] if m.get("Status") == "New MO"]), 200


@app.route("/mos/search", methods=["GET"])
def search_mo():
    mo_number = request.args.get("mo_number") or request.args.get("order_number")
    if not mo_number:
        return jsonify([]), 200
    mo = find_mo(mo_number)
    return jsonify([mo] if mo else []), 200


@app.route("/mos/<mo_number>", methods=["GET"])
def get_mo_single(mo_number):
    mo = find_mo(mo_number)
    return jsonify(mo if mo else {}), (200 if mo else 404)


@app.route("/mo_item_counter", methods=["GET"])
def mo_item_counter():
    return jsonify({"count": len(DB["mos"])}), 200


# ===========================================================================
# BOM / MATERIAL LINES ("mo_material" == real issued-qty source of truth)
# ===========================================================================

@app.route("/mo_line", methods=["GET"])
def get_mo_line():
    return jsonify(DB["mo_line"]), 200


@app.route("/mo_line/search", methods=["GET"])
def search_mo_line():
    mo_number = (request.args.get("mo_number") or "").upper()
    return jsonify([l for l in DB["mo_line"] if l["Mo_Number"].upper() == mo_number]), 200


@app.route("/mo_material/<int:moh_id>", methods=["GET"])
def get_mo_material(moh_id):
    lines = [l for l in DB["mo_material"] if l["moh_id"] == moh_id]
    lines.sort(key=lambda l: l["Line_Number"])
    return jsonify(lines), 200


@app.route("/mo_material/update_qty_issued", methods=["POST"])
def update_qty_issued():
    data = request.get_json(force=True, silent=True) or {}
    moh_id = data.get("moh_id")
    items = data.get("items", [])
    mo = find_mo_by_moh(moh_id)
    if not mo or not items:
        return jsonify({"error": "moh_id and items are required"}), 400

    with LOCK:
        updated = 0
        touched_items = set()
        for item in items:
            item_number = item.get("item_number")
            qty_picked = float(item.get("qty_picked", 0) or 0)
            mode = item.get("mode", "normal")
            if not item_number or qty_picked <= 0:
                continue
            line = next((l for l in DB["mo_material"]
                        if l["moh_id"] == moh_id and l["item_number"] == item_number), None)
            if not line:
                continue
            if mode == "reissue":
                line["Qty_Scrap"] = round(line["Qty_Scrap"] + qty_picked, 2)
                line["qty_scrap"] = line["Qty_Scrap"]
            else:
                line["Qty_Issued"] = round(line["Qty_Issued"] + qty_picked, 2)
                line["qty_issued"] = line["Qty_Issued"]
                line["Status_id"] = 86 if line["Qty_Issued"] >= line["Qty_Required"] else 145
            # Decrement bulk warehouse stock
            for w in DB["whmoitems"]:
                if w["item_number"] == item_number:
                    w["total_stock"] = max(0.0, round(w["total_stock"] - qty_picked, 2))
                    w["stock_on_hand"] = w["total_stock"]
                    w["updated_at"] = now_iso()
            # Log to reports / bulk issue history
            DB["reports"].append({
                "id": next_id("report_id"), "action": "reissue" if mode == "reissue" else "issue",
                "mo": mo["mo_number"], "item": item_number, "qty": qty_picked,
                "batch_no": f"B{next_id('report_id') + 9000}", "mode": mode,
                "issued_by": data.get("issued_by", "DANI"),
                "time": now_iso(), "notes": None, "items": None, "created_at": now_iso(),
            })
            touched_items.add(item_number)
            updated += 1

        # Recompute header-level Qty_Issued + status
        mo_lines = [l for l in DB["mo_material"] if l["moh_id"] == moh_id]
        total_required = sum(l["Qty_Required"] for l in mo_lines)
        total_issued = sum(l["Qty_Issued"] for l in mo_lines)
        mo["Qty_Issued"] = round(total_issued, 1)
        if mo.get("Status") in ("New MO",):
            mo["Status"] = "Started"
            mo["status"] = "Started"
        if total_required > 0 and total_issued >= total_required:
            mo["Status"] = "Issued"
            mo["status"] = "Issued"
            mo["Status_ID"] = 86
            mo["status_id"] = 86
        for item_number in touched_items:
            recompute_whmoitem(item_number)
        save_db()

    return jsonify({"status": "ok", "updated": updated}), 200


# ===========================================================================
# TRANSFERS
# ===========================================================================

@app.route("/mo_transfer", methods=["GET"])
def get_mo_transfer():
    moh_id = request.args.get("moh_id")
    mo_number = request.args.get("mo_number")
    rows = DB["mo_transfer"]
    if moh_id:
        rows = [r for r in rows if str(r["moh_ID"]) == str(moh_id)]
    if mo_number:
        rows = [r for r in rows if r["mo_number"].upper() == mo_number.upper()]
    return jsonify(rows), 200


@app.route("/mo_transfers_batch", methods=["GET"])
def get_mo_transfers_batch():
    ids = request.args.get("moh_ids", "")
    id_set = {s.strip() for s in ids.split(",") if s.strip()}
    rows = [r for r in DB["mo_transfer"] if str(r["moh_ID"]) in id_set] if id_set else DB["mo_transfer"]
    return jsonify(rows), 200


# ===========================================================================
# STATUS HISTORY / DASHBOARD
# ===========================================================================

@app.route("/mo_status_change", methods=["GET"])
def get_mo_status_change():
    mo_number = request.args.get("mo_number")
    rows = DB["status_events"]
    if mo_number:
        rows = [r for r in rows if r["mo_number"].upper() == mo_number.upper()]
    return jsonify(sorted(rows, key=lambda r: r["event_time"], reverse=True)), 200


@app.route("/status_history", methods=["GET"])
def get_status_history():
    mo_number = request.args.get("mo")
    rows = DB["status_events"]
    if mo_number:
        rows = [r for r in rows if r["mo_number"].upper() == mo_number.upper()]
    return jsonify(sorted(rows, key=lambda r: r["event_time"], reverse=True)), 200


@app.route("/mo_status_change/universal", methods=["GET"])
@app.route("/universal/mo_status_events", methods=["GET"])
def get_universal_status_events():
    return jsonify(DB["status_events"]), 200


@app.route("/universal/mo_headers", methods=["GET"])
def get_universal_mo_headers():
    return jsonify([{"moh_id": m["moh_id"], "Mo_Number": m["mo_number"],
                     "date_required": m["date_required"]} for m in DB["mos"]]), 200


# ===========================================================================
# BULK WAREHOUSE STOCK / SHORTAGE CONTROL (WHMOItems)
# ===========================================================================

@app.route("/whmoitems", methods=["GET"])
@app.route("/item_available", methods=["GET"])
def get_whmoitems():
    q = request.args.get("q")
    rows = DB["whmoitems"]
    if q:
        rows = [r for r in rows if r["item_number"].startswith(q)]
    return jsonify(rows), 200


@app.route("/whmoitems/update", methods=["POST"])
def update_whmoitem():
    data = request.get_json(force=True, silent=True) or {}
    item_number = data.get("item_number")
    with LOCK:
        for w in DB["whmoitems"]:
            if w["item_number"] == item_number:
                if "total_stock" in data:
                    w["total_stock"] = float(data["total_stock"])
                    w["stock_on_hand"] = w["total_stock"]
                if "location" in data:
                    w["location"] = data["location"]
                w["updated_at"] = now_iso()
                recompute_whmoitem(item_number)
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/whmoitems/refresh_from_mrp", methods=["POST"])
def refresh_from_mrp():
    with LOCK:
        for w in DB["whmoitems"]:
            recompute_whmoitem(w["item_number"])
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/whmoitems/ensure_all_mo_items", methods=["POST"])
@app.route("/whmoitems/update_descriptions", methods=["POST"])
@app.route("/whmoitems/sync_from_mo_line", methods=["POST"])
@app.route("/whmoitems/sync", methods=["POST"])
def whmoitems_maintenance_noop():
    # Real backend does catalogue-maintenance jobs here (sync new items in,
    # refresh descriptions, etc). The demo catalogue is fixed and already
    # internally consistent, so these are safe no-ops.
    return jsonify({"status": "ok"}), 200


@app.route("/bulk_issue/latest_number", methods=["GET"])
def bulk_issue_latest_number():
    return jsonify({"latest": f"B{DB['next_ids'].get('report_id', 1) + 9000}"}), 200


# ===========================================================================
# REISSUE REQUESTS
# ===========================================================================

@app.route("/reissue_requests/create", methods=["POST"])
def create_reissue_request():
    data = request.get_json(force=True, silent=True) or {}
    mo_number = data.get("mo_number")
    moh_id = data.get("moh_ID") or data.get("moh_id")
    requested_by = data.get("requested_by")
    reason = data.get("reason")
    items = data.get("items", [])
    if not all([mo_number, moh_id, requested_by, reason, items]):
        return jsonify({"error": "Missing required fields"}), 400
    u = find_user(requested_by) or {}
    with LOCK:
        entry = {
            "id": next_id("reissue_id"), "mo_number": mo_number, "moh_ID": moh_id,
            "requested_by": requested_by,
            "requested_by_name": f"{u.get('name','')} {u.get('surname','')}".strip() or requested_by,
            "reason": reason, "items": items, "status": data.get("status", "pending"),
            "requested_at": now_iso(), "reviewed_by": None, "reviewed_by_name": None,
            "reviewed_at": None, "admin_response": None,
        }
        DB["reissue_requests"].append(entry)
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/reissue_requests/list", methods=["GET"])
def list_reissue_requests():
    status = request.args.get("status")
    rows = DB["reissue_requests"]
    if status:
        rows = [r for r in rows if r["status"] == status]
    return jsonify(sorted(rows, key=lambda r: r["requested_at"], reverse=True)), 200


@app.route("/reissue_requests/update_status", methods=["POST"])
def update_reissue_status():
    data = request.get_json(force=True, silent=True) or {}
    request_id = data.get("request_id")
    status = data.get("status")
    reviewed_by = data.get("reviewed_by")
    admin_response = data.get("admin_response", "")
    if not all([request_id, status, reviewed_by]):
        return jsonify({"error": "Missing required fields"}), 400
    u = find_user(reviewed_by) or {}
    with LOCK:
        for r in DB["reissue_requests"]:
            if r["id"] == request_id:
                r["status"] = status
                r["reviewed_by"] = reviewed_by
                r["reviewed_by_name"] = f"{u.get('name','')} {u.get('surname','')}".strip() or reviewed_by
                r["reviewed_at"] = now_iso()
                r["admin_response"] = admin_response
        save_db()
    return jsonify({"status": "ok"}), 200


# ===========================================================================
# REPORTS (bulk issue / activity log)
# ===========================================================================

@app.route("/reports", methods=["GET"])
def get_reports():
    limit = int(request.args.get("limit", 1000))
    mo_number = request.args.get("mo_number")
    rows = DB["reports"]
    if mo_number:
        rows = [r for r in rows if r["mo"].upper() == mo_number.upper()]
    rows = sorted(rows, key=lambda r: r["time"], reverse=True)[:limit]
    return jsonify({"reports": rows, "count": len(rows)}), 200


@app.route("/reports", methods=["POST"])
def create_report():
    data = request.get_json(force=True, silent=True) or {}
    with LOCK:
        entry = {
            "id": next_id("report_id"), "action": data.get("action", "issue"),
            "mo": data.get("mo_number") or data.get("mo"), "item": data.get("item_number") or data.get("item"),
            "qty": data.get("qty"), "batch_no": data.get("batch_no"), "mode": data.get("mode", "normal"),
            "issued_by": data.get("issued_by"), "time": now_iso(), "notes": data.get("notes"),
            "items": data.get("items"), "created_at": now_iso(),
        }
        DB["reports"].append(entry)
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/reports/bulk", methods=["POST"])
def create_reports_bulk():
    data = request.get_json(force=True, silent=True) or {}
    rows = data.get("reports", [])
    with LOCK:
        for r in rows:
            DB["reports"].append({
                "id": next_id("report_id"), "action": r.get("action", "issue"),
                "mo": r.get("mo_number") or r.get("mo"), "item": r.get("item_number") or r.get("item"),
                "qty": r.get("qty"), "batch_no": r.get("batch_no"), "mode": r.get("mode", "normal"),
                "issued_by": r.get("issued_by"), "time": now_iso(), "notes": r.get("notes"),
                "items": r.get("items"), "created_at": now_iso(),
            })
        save_db()
    return jsonify({"status": "ok", "count": len(rows)}), 200


# ===========================================================================
# MO COMMENTS
# ===========================================================================

@app.route("/mo-comments", methods=["POST"])
def add_comment():
    data = request.get_json(force=True, silent=True) or {}
    with LOCK:
        entry = {
            "id": next_id("comment_id"), "mo_number": data.get("mo_number"),
            "comment": data.get("comment"), "created_by": data.get("created_by", "user"),
            "created_at": now_iso(),
        }
        DB["mo_comments"].append(entry)
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/mo-comments/<mo_number>", methods=["GET"])
def get_comments(mo_number):
    rows = [c for c in DB["mo_comments"] if c["mo_number"].upper() == mo_number.upper()]
    return jsonify(rows), 200


@app.route("/mo-comments/batch", methods=["POST"])
def get_comments_batch():
    data = request.get_json(force=True, silent=True) or {}
    mo_numbers = {m.upper() for m in data.get("mo_numbers", [])}
    rows = [c for c in DB["mo_comments"] if c["mo_number"].upper() in mo_numbers]
    return jsonify(rows), 200


# ===========================================================================
# PRODUCTION USERS / WORKSTATIONS
# ===========================================================================

@app.route("/production_users", methods=["GET"])
def get_production_users():
    return jsonify([u for u in DB["production_users"] if u["is_active"]]), 200


@app.route("/production_users/summary", methods=["GET"])
def get_production_users_summary():
    ws_map = {w["id"]: w["name"] for w in DB["workstations"]}
    results = []
    for u in DB["production_users"]:
        if not u["is_active"]:
            continue
        assigned_mos = {a["mo_number"] for a in DB["mo_assignments"] if a["production_user_id"] == u["id"]}
        on_break = False  # demo: nobody permanently on break, kept simple/deterministic
        current_mo = next(iter(assigned_mos), None)
        results.append({
            "id": u["id"], "employee_username": u["employee_username"], "full_name": u["full_name"],
            "workstations": ws_map.get(u["workstation_id"], "Unassigned"),
            "total_mos": len(assigned_mos), "on_break": on_break, "break_name": None,
            "activity_status": "Working" if current_mo else "Offline",
            "current_mo": current_mo, "last_action": "Picking" if current_mo else None,
            "last_time": now_iso(),
        })
    return jsonify(results), 200


@app.route("/production_users/device_session", methods=["GET"])
def get_production_user_device_session():
    return jsonify({"active": False}), 200


@app.route("/production_users/activity", methods=["GET"])
def get_production_user_activity():
    return jsonify([]), 200


@app.route("/production_users/completions", methods=["GET"])
def get_production_user_completions():
    username = request.args.get("username")
    rows = [c for c in DB["workstation_completions"] if c.get("created_by") == username]
    return jsonify(rows), 200


@app.route("/mo_completions/summary", methods=["GET"])
def get_mo_completions_summary():
    mo_numbers_raw = request.args.get("mo_numbers", "")
    single = request.args.get("mo_number", "")
    mo_numbers = [m.strip().upper() for m in mo_numbers_raw.split(",") if m.strip()]
    if single.strip():
        mo_numbers.append(single.strip().upper())
    mo_numbers = list(dict.fromkeys(mo_numbers))
    if not mo_numbers:
        return jsonify([]), 200
    totals = {}
    for c in DB["workstation_completions"]:
        mo = c["mo_number"].upper()
        if mo in mo_numbers:
            totals[mo] = totals.get(mo, 0) + c["qty_completed"]
    return jsonify([{"mo_number": k, "qty_completed": v} for k, v in totals.items()]), 200


@app.route("/production_workstations", methods=["GET"])
def get_production_workstations():
    return jsonify([w for w in DB["workstations"] if w["is_active"]]), 200


@app.route("/mo_workstation_history", methods=["GET"])
def get_mo_workstation_history():
    mo_number = request.args.get("mo_number")
    rows = WORKSTATION_HISTORY
    if mo_number:
        rows = [r for r in rows if r["mo_number"].upper() == mo_number.upper()]
    return jsonify(sorted(rows, key=lambda r: r["changed_at"], reverse=True)), 200


@app.route("/mo_workstation_latest", methods=["GET"])
def get_mo_workstation_latest():
    mo_numbers = {m.strip().upper() for m in (request.args.get("mo_numbers", "")).split(",") if m.strip()}
    latest = {}
    for r in WORKSTATION_HISTORY:
        mo = r["mo_number"].upper()
        if mo_numbers and mo not in mo_numbers:
            continue
        prev = latest.get(mo)
        if not prev or r["changed_at"] > prev["changed_at"]:
            latest[mo] = r
    return jsonify(list(latest.values())), 200


@app.route("/workstations/<int:ws_id>/users", methods=["GET"])
def get_workstation_users(ws_id):
    return jsonify([u for u in DB["production_users"] if u["workstation_id"] == ws_id]), 200


@app.route("/workstations/assign_user", methods=["POST"])
def assign_user_to_workstation():
    data = request.get_json(force=True, silent=True) or {}
    user_id = data.get("user_id") or data.get("production_user_id")
    workstation_id = data.get("workstation_id")
    with LOCK:
        for u in DB["production_users"]:
            if u["id"] == user_id:
                u["workstation_id"] = workstation_id
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/workstations/remove_user", methods=["POST"])
def remove_user_from_workstation():
    data = request.get_json(force=True, silent=True) or {}
    user_id = data.get("user_id") or data.get("production_user_id")
    with LOCK:
        for u in DB["production_users"]:
            if u["id"] == user_id:
                u["workstation_id"] = None
        save_db()
    return jsonify({"status": "ok"}), 200


# ===========================================================================
# MO ASSIGNMENTS (workstation routing) + priority
# ===========================================================================

@app.route("/mo_assignments", methods=["GET"])
def list_mo_assignments():
    mo_number = request.args.get("mo_number")
    rows = DB["mo_assignments"]
    if mo_number:
        rows = [r for r in rows if r["mo_number"].upper() == mo_number.upper()]
    return jsonify(rows), 200


@app.route("/mo_assignments/create", methods=["POST"])
def create_mo_assignment():
    data = request.get_json(force=True, silent=True) or {}
    mo_number = data.get("mo_number")
    moh_id = data.get("moh_ID") or data.get("moh_id")
    if not mo_number or not moh_id:
        return jsonify({"error": "mo_number and moh_ID are required"}), 400
    with LOCK:
        specific_users = data.get("production_user_id")
        if isinstance(specific_users, str):
            try:
                specific_users = json.loads(specific_users)
            except Exception:
                specific_users = []
        specific_users = specific_users or []
        if specific_users:
            for su in specific_users:
                uid = su.get("user_id") or su.get("production_user_id")
                pu = next((p for p in DB["production_users"] if p["id"] == uid), None)
                ws = next((w for w in DB["workstations"] if w["id"] == su.get("workstation_id")), None)
                existing = next((a for a in DB["mo_assignments"]
                                 if a["mo_number"] == mo_number and a["production_user_id"] == uid), None)
                payload = {
                    "mo_number": mo_number, "moh_ID": moh_id,
                    "employee_username": pu["employee_username"] if pu else su.get("employee_username"),
                    "user_name": pu["full_name"] if pu else su.get("name"),
                    "workstation": ws["name"] if ws else su.get("workstation_name"),
                    "workstation_id": ws["id"] if ws else su.get("workstation_id"),
                    "production_user_id": uid, "assigned_by": data.get("assigned_by", "unknown"),
                    "assigned_at": now_iso(), "is_priority": data.get("is_priority", 0),
                    "notes": data.get("notes"), "workstations": None,
                }
                if existing:
                    existing.update(payload)
                else:
                    payload["id"] = next_id("assignment_id")
                    DB["mo_assignments"].append(payload)
        else:
            DB["mo_assignments"].append({
                "id": next_id("assignment_id"), "mo_number": mo_number, "moh_ID": moh_id,
                "employee_username": None, "user_name": None, "workstation": None, "workstation_id": None,
                "production_user_id": None, "assigned_by": data.get("assigned_by", "unknown"),
                "assigned_at": now_iso(), "is_priority": data.get("is_priority", 0),
                "notes": data.get("notes"), "workstations": data.get("workstations", []),
            })
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/mo_assignments/<mo_number>", methods=["DELETE"])
def delete_mo_assignment(mo_number):
    with LOCK:
        DB["mo_assignments"] = [a for a in DB["mo_assignments"] if a["mo_number"].upper() != mo_number.upper()]
        save_db()
    return jsonify({"status": "ok"}), 200


@app.route("/mo_assignments/check_priority/<mo_number>", methods=["GET"])
def check_priority(mo_number):
    mo = find_mo(mo_number)
    return jsonify({"is_priority": bool(mo and mo.get("is_priority"))}), 200


@app.route("/mo_assignments/set_priority", methods=["POST"])
def set_priority(*args, **kwargs):
    data = request.get_json(force=True, silent=True) or {}
    mo = find_mo(data.get("mo_number"))
    with LOCK:
        if mo:
            mo["is_priority"] = 1 if data.get("is_priority") else 0
        for a in DB["mo_assignments"]:
            if a["mo_number"].upper() == (data.get("mo_number") or "").upper():
                a["is_priority"] = mo["is_priority"] if mo else 0
        save_db()
    return jsonify({"status": "ok"}), 200


# ===========================================================================
# MO ITEM ASSIGNMENTS (per-user picking claims) - lightweight demo stub
# ===========================================================================

@app.route("/mo-item-assignments/<mo_number>", methods=["GET"])
def get_mo_item_assignments(mo_number):
    return jsonify([]), 200


@app.route("/mo-item-assignments/<mo_number>", methods=["DELETE"])
def delete_mo_item_assignments(mo_number):
    return jsonify({"status": "ok"}), 200


# ===========================================================================
# MO SESSIONS / ASSIST REQUESTS / CORRECTION REQUESTS - demo stubs (return
# empty / no-op so the UI doesn't error, without pretending these workflows
# have real demo data behind them)
# ===========================================================================

@app.route("/mo-sessions/<mo_number>", methods=["GET"])
def mo_sessions(mo_number):
    return jsonify({"active_users": []}), 200


@app.route("/assist-requests/pending/<int:user_id>", methods=["GET"])
@app.route("/assist-requests/approved/<int:user_id>", methods=["GET"])
@app.route("/assist-requests/declined/<int:user_id>", methods=["GET"])
def assist_requests_empty(user_id):
    return jsonify([]), 200


@app.route("/correction-requests/pending", methods=["GET"])
def correction_requests_pending():
    return jsonify([]), 200


@app.route("/correction-requests/history", methods=["GET"])
def correction_requests_history():
    return jsonify([]), 200


# ===========================================================================
# ITEM CATALOG helpers
# ===========================================================================

@app.route("/ic_items/descriptions", methods=["GET"])
def ic_items_descriptions():
    return jsonify({m["item_number"]: m["description"] for m in DB["materials"]}), 200


@app.route("/", methods=["GET"])
def root():
    # Serves the frontend (public/index.html) so the API and the UI live on
    # exactly one origin - locally that's 127.0.0.1:5057, on Render it's
    # whatever URL Render assigns. No separate static host needed.
    index_path = os.path.join(PUBLIC_DIR, "index.html")
    if os.path.exists(index_path):
        return send_from_directory(PUBLIC_DIR, "index.html")
    return jsonify({
        "service": "Bolide Tanzania WMS DEMO backend", "status": "ok",
        "mos": len(DB["mos"]), "port": PORT,
        "note": "public/index.html not found - API-only mode",
    }), 200


@app.route("/api/status", methods=["GET"])
def api_status():
    return jsonify({
        "service": "Bolide Tanzania WMS DEMO backend", "status": "ok",
        "mos": len(DB["mos"]), "port": PORT,
    }), 200


@app.route("/health", methods=["GET", "POST"])
def health():
    return jsonify({"status": "ok"}), 200


if __name__ == "__main__":
    print(f"[DEMO SERVER] {len(DB['mos'])} MOs loaded from "
          f"{'demo_data.json (saved state)' if os.path.exists(STATE_PATH) else 'demo_data_seed.json (fresh seed)'}")
    print(f"[DEMO SERVER] Listening on http://127.0.0.1:{PORT} (frontend + API, same origin)")
    # threaded=True matters: the real frontend fires dozens of concurrent
    # fetches (per-MO transfer totals, comments, assignments, etc.) on every
    # page. Flask's dev server is single-threaded by default and would
    # serialize all of them, making pages that fan out requests look empty
    # or stuck for many seconds.
    # host=0.0.0.0 so this also works when run directly (not via gunicorn)
    # inside a container/Render instance, not just on localhost.
    app.run(host="0.0.0.0", port=PORT, debug=False, threaded=True)
